"""Persists generated Terraform resources."""
import json
import os
import re
from datetime import datetime
from typing import List, Optional

from scalr_tfc_migrate.hcl import (
    AbstractTerraformResource,
    TerraformDataSource,
    TerraformResource,
    extract_resources,
    transform_name,
)


class ResourceManager:
    def __init__(self, output_dir: str) -> None:
        self.resources: List[TerraformResource] = []
        self.data_sources: List[TerraformDataSource] = []
        self.output_dir = output_dir
        self._load_existing_data_sources()
        self._load_existing_resources()

    def _load_existing_resources(self):
        """Load existing resources from main.tf if it exists."""
        main_tf_path = os.path.join(self.output_dir, "main.tf")
        if not os.path.exists(main_tf_path):
            return

        regexp = r'resource\s+"([^"]+)"\s+"([^"]+)"\s*{([^}]+)}'

        with open(main_tf_path, "r") as f:
            for match in re.finditer(regexp, f.read(), re.DOTALL):
                resource_type, name, attrs_block = match.groups()
                self.resources.append(
                    TerraformResource(resource_type, name, extract_resources(attrs_block))
                )

    def _load_existing_data_sources(self):
        """Load existing resources from main.tf if it exists."""
        main_tf_path = os.path.join(self.output_dir, "main.tf")
        if not os.path.exists(main_tf_path):
            return

        regexp = r'data\s+"([^"]+)"\s+"([^"]+)"\s*{([^}]+)}'

        with open(main_tf_path, "r") as f:
            for match in re.finditer(regexp, f.read(), re.DOTALL):
                resource_type, name, attrs_block = match.groups()
                self.data_sources.append(
                    TerraformDataSource(resource_type, name, extract_resources(attrs_block))
                )

    def add_resource(self, resource: TerraformResource):
        """Add a resource if it doesn't already exist."""
        # Check if resource already exists
        if self.has_resource(resource.resource_type, resource.name):
            return

        self.resources.append(resource)

    def add_data_source(self, data_source: TerraformDataSource):
        """Add a resource if it doesn't already exist."""
        # Check if resource already exists
        if self.has_data_source(data_source.resource_type, data_source.name):
            return
        self.data_sources.append(data_source)

    def has_resource(self, resource_type: str, name: str) -> bool:
        converted = transform_name(name)

        for existing in self.resources:
            if existing.resource_type == resource_type and existing.name == converted:
                return True

        return False

    def get_resource(self, resource_type: str, name: str) -> Optional[AbstractTerraformResource]:
        converted = transform_name(name)
        for existing in self.data_sources + self.resources:
            if existing.resource_type == resource_type and existing.name == converted:
                return existing
        return None

    def has_data_source(self, resource_type: str, name: str) -> bool:
        converted = transform_name(name)

        for existing in self.data_sources:
            if existing.resource_type == resource_type and existing.name == converted:
                return True

        return False

    def write_resources(self, output_dir: str):
        os.makedirs(output_dir, exist_ok=True)

        # Write main.tf
        main_tf_path = os.path.join(output_dir, "main.tf")
        file_exists = os.path.exists(main_tf_path)

        with open(main_tf_path, "a" if file_exists else "w") as f:
            if not file_exists:
                f.write("# Generated by Scalr Migrator\n")
                f.write(f"# Generated at: {datetime.now().isoformat()}\n\n")
                # Add required provider block only for new file
                f.write('''terraform {
  required_providers {
    scalr = {
      source = "scalr/scalr"
    }
  }
}

''')

            # Only write new resources
            existing_resources = set()
            if file_exists:
                with open(main_tf_path, "r") as existing:
                    content = existing.read()
                    for resource in (self.resources + self.data_sources):
                        pattern = f'{resource.hcl_resource_type} "{resource.resource_type}" "{resource.name}"'
                        if pattern in content:
                            existing_resources.add((resource.resource_type, resource.name))

            # Write resource blocks
            for resource in (self.data_sources + self.resources):
                if (resource.resource_type, resource.name) not in existing_resources:
                    rs: str = resource.to_hcl()
                    f.write(rs.replace("'", '"') + "\n\n")

        # Write imports.tf
        imports_path = os.path.join(output_dir, "imports.tf")
        with open(imports_path, "w") as f:
            f.write("# Generated by Scalr Migrator\n")
            f.write(f"# Generated at: {datetime.now().isoformat()}\n\n")
            f.write("# This file contains import blocks for resources.\n")
            f.write("# You can safely remove this file after successful import.\n\n")

            for resource in self.resources:
                if resource.id and (resource.resource_type, resource.name) not in existing_resources:
                    f.write(f'import {{\n')
                    f.write(f'  to = {resource.resource_type}.{resource.name}\n')
                    f.write(f'  id = "{resource.id}"\n')
                    f.write(f'}}\n\n')

